project_id: '808262'
api_token_env: CROWDIN_PERSONAL_TOKEN
preserve_hierarchy: true
files:
  - source: /i18n/en/**/*
    translation: /i18n/%language%/**/%original_file_name%
  - source: /docs/**/*
    translation: /i18n/%language%/docusaurus-plugin-content-docs/current/**/%original_file_name%
  - source: /blog/**/*
    translation: /i18n/%language%/docusaurus-plugin-content-blog/**/%original_file_name%
